// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TuColmadoRD.Infrastructure.Persistence.Contexts;

#nullable disable

namespace TuColmadoRD.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TuColmadoDbContext))]
    [Migration("20260317212539_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Audit.AuditTrail", b =>
                {
                    b.ToTable("AuditTrails", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.CustomerAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerAccounts", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.DebtTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerAccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerAccountId");

                    b.ToTable("DebtTransactions", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.FiscalReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NCF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("FiscalReceipts", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.FiscalSequence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("CurrentNumber")
                        .HasColumnType("bigint");

                    b.Property<long>("EndNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FiscalSequences", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.Tax", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Taxes", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.HumanResources.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.HumanResources.WorkShift", b =>
                {
                    b.ToTable("WorkShifts", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IconPath")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UnitType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.UnitConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Factor")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("FromUnitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToUnitId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FromUnitId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ToUnitId");

                    b.ToTable("UnitConversions", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.UnitOfMeasureEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsFractionable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasures", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Logistics.DeliveryOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeliveryPersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryPersonId");

                    b.ToTable("DeliveryOrders", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Logistics.DeliveryPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("VehiclePlate")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryPersons", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.PurchaseDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseDetails", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("PurchaseOrders", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Suppliers", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.SaleDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SaleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("SaleDetails", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.CashBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("CashBoxes", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.CashDrawer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.ToTable("CashDrawers", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CashBoxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReferenceNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CashBoxId");

                    b.ToTable("Expenses", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.PettyCash", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("PettyCashes", (string)null);
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.Customer", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Phone", "ContactPhone", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ContactPhone");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Cedula", "DocumentId", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("DocumentId");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Address", "HomeAddress", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("HouseNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Address_HouseNumber");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Address_Province");

                            b1.Property<string>("Reference")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Address_Reference");

                            b1.Property<string>("Sector")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Address_Sector");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Address_Street");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("ContactPhone");

                    b.Navigation("DocumentId")
                        .IsRequired();

                    b.Navigation("HomeAddress");

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.CustomerAccount", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Customers.Customer", null)
                        .WithOne("Account")
                        .HasForeignKey("TuColmadoRD.Core.Domain.Entities.Customers.CustomerAccount", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "Balance", b1 =>
                        {
                            b1.Property<Guid>("CustomerAccountId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Balance");

                            b1.HasKey("CustomerAccountId");

                            b1.ToTable("CustomerAccounts");

                            b1.WithOwner()
                                .HasForeignKey("CustomerAccountId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "CreditLimit", b1 =>
                        {
                            b1.Property<Guid>("CustomerAccountId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CreditLimit");

                            b1.HasKey("CustomerAccountId");

                            b1.ToTable("CustomerAccounts");

                            b1.WithOwner()
                                .HasForeignKey("CustomerAccountId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("CustomerAccountId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("CustomerAccountId");

                            b1.ToTable("CustomerAccounts");

                            b1.WithOwner()
                                .HasForeignKey("CustomerAccountId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("CreditLimit")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.DebtTransaction", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Customers.CustomerAccount", null)
                        .WithMany()
                        .HasForeignKey("CustomerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("DebtTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("DebtTransactionId");

                            b1.ToTable("DebtTransactions");

                            b1.WithOwner()
                                .HasForeignKey("DebtTransactionId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("DebtTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("DebtTransactionId");

                            b1.ToTable("DebtTransactions");

                            b1.WithOwner()
                                .HasForeignKey("DebtTransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.FiscalReceipt", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Rnc", "BuyerRnc", b1 =>
                        {
                            b1.Property<Guid>("FiscalReceiptId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("BuyerRnc");

                            b1.HasKey("FiscalReceiptId");

                            b1.ToTable("FiscalReceipts");

                            b1.WithOwner()
                                .HasForeignKey("FiscalReceiptId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("FiscalReceiptId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("FiscalReceiptId");

                            b1.ToTable("FiscalReceipts");

                            b1.WithOwner()
                                .HasForeignKey("FiscalReceiptId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "TotalTaxed", b1 =>
                        {
                            b1.Property<Guid>("FiscalReceiptId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalTaxed");

                            b1.HasKey("FiscalReceiptId");

                            b1.ToTable("FiscalReceipts");

                            b1.WithOwner()
                                .HasForeignKey("FiscalReceiptId");
                        });

                    b.Navigation("BuyerRnc");

                    b.Navigation("TenantId")
                        .IsRequired();

                    b.Navigation("TotalTaxed")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.FiscalSequence", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("FiscalSequenceId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("FiscalSequenceId");

                            b1.ToTable("FiscalSequences");

                            b1.WithOwner()
                                .HasForeignKey("FiscalSequenceId");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Fiscal.Tax", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TaxRate", "Rate", b1 =>
                        {
                            b1.Property<Guid>("TaxId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("RateName");

                            b1.Property<decimal>("Percentage")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("RatePercentage");

                            b1.HasKey("TaxId");

                            b1.ToTable("Taxes");

                            b1.WithOwner()
                                .HasForeignKey("TaxId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("TaxId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("TaxId");

                            b1.ToTable("Taxes");

                            b1.WithOwner()
                                .HasForeignKey("TaxId");
                        });

                    b.Navigation("Rate")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.HumanResources.Employee", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Cedula", "IdCard", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("IdCard");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Phone", "Phone", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Phone");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("IdCard");

                    b.Navigation("Phone");

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.Category", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.Product", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "CostPrice", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CostPrice");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TaxRate", "IscRate", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("IscName");

                            b1.Property<decimal>("Percentage")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("IscPercentage");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TaxRate", "ItbisRate", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ItbisName");

                            b1.Property<decimal>("Percentage")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("ItbisPercentage");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Quantity", "MinStock", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("MinStockUnitType");

                            b1.Property<string>("UnitLabel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("MinStockUnitLabel");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("MinStockQuantity");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "SalePrice", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SalePrice");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Quantity", "StockQuantity", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("StockUnitType");

                            b1.Property<string>("UnitLabel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("StockUnitLabel");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("StockQuantity");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("ProductId");

                            b1.ToTable("Products");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("CostPrice")
                        .IsRequired();

                    b.Navigation("IscRate");

                    b.Navigation("ItbisRate")
                        .IsRequired();

                    b.Navigation("MinStock")
                        .IsRequired();

                    b.Navigation("SalePrice")
                        .IsRequired();

                    b.Navigation("StockQuantity")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Inventory.UnitConversion", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Inventory.UnitOfMeasureEntity", "FromUnit")
                        .WithMany()
                        .HasForeignKey("FromUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Inventory.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Inventory.UnitOfMeasureEntity", "ToUnit")
                        .WithMany()
                        .HasForeignKey("ToUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("UnitConversionId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("UnitConversionId");

                            b1.ToTable("UnitConversions");

                            b1.WithOwner()
                                .HasForeignKey("UnitConversionId");
                        });

                    b.Navigation("FromUnit");

                    b.Navigation("TenantId")
                        .IsRequired();

                    b.Navigation("ToUnit");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Logistics.DeliveryOrder", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Logistics.DeliveryPerson", null)
                        .WithMany()
                        .HasForeignKey("DeliveryPersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Address", "Destination", b1 =>
                        {
                            b1.Property<Guid>("DeliveryOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("HouseNumber")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("Destination_HouseNumber");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Destination_Province");

                            b1.Property<string>("Reference")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("Destination_Reference");

                            b1.Property<string>("Sector")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Destination_Sector");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Destination_Street");

                            b1.HasKey("DeliveryOrderId");

                            b1.ToTable("DeliveryOrders");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryOrderId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("DeliveryOrderId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("DeliveryOrderId");

                            b1.ToTable("DeliveryOrders");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryOrderId");
                        });

                    b.Navigation("Destination")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Logistics.DeliveryPerson", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Phone", "ContactPhone", b1 =>
                        {
                            b1.Property<Guid>("DeliveryPersonId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ContactPhone");

                            b1.HasKey("DeliveryPersonId");

                            b1.ToTable("DeliveryPersons");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryPersonId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("DeliveryPersonId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("DeliveryPersonId");

                            b1.ToTable("DeliveryPersons");

                            b1.WithOwner()
                                .HasForeignKey("DeliveryPersonId");
                        });

                    b.Navigation("ContactPhone");

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.PurchaseDetail", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Inventory.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Purchasing.PurchaseOrder", null)
                        .WithMany("Details")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("PurchaseDetailId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("UnitType");

                            b1.Property<string>("UnitLabel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("UnitLabel");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("Quantity");

                            b1.HasKey("PurchaseDetailId");

                            b1.ToTable("PurchaseDetails");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseDetailId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "SubTotal", b1 =>
                        {
                            b1.Property<Guid>("PurchaseDetailId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SubTotal");

                            b1.HasKey("PurchaseDetailId");

                            b1.ToTable("PurchaseDetails");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseDetailId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "UnitCost", b1 =>
                        {
                            b1.Property<Guid>("PurchaseDetailId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("UnitCost");

                            b1.HasKey("PurchaseDetailId");

                            b1.ToTable("PurchaseDetails");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseDetailId");
                        });

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("SubTotal")
                        .IsRequired();

                    b.Navigation("UnitCost")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.PurchaseOrder", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Purchasing.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("PurchaseOrderId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("PurchaseOrderId");

                            b1.ToTable("PurchaseOrders");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("PurchaseOrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalAmount");

                            b1.HasKey("PurchaseOrderId");

                            b1.ToTable("PurchaseOrders");

                            b1.WithOwner()
                                .HasForeignKey("PurchaseOrderId");
                        });

                    b.Navigation("TenantId")
                        .IsRequired();

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.Supplier", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Phone", "ContactPhone", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("ContactPhone");

                            b1.HasKey("SupplierId");

                            b1.ToTable("Suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Rnc", "TaxId", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("character varying(15)")
                                .HasColumnName("TaxId");

                            b1.HasKey("SupplierId");

                            b1.ToTable("Suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("SupplierId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("SupplierId");

                            b1.ToTable("Suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId");
                        });

                    b.Navigation("ContactPhone");

                    b.Navigation("TaxId")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.Sale", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "SubTotal", b1 =>
                        {
                            b1.Property<Guid>("SaleId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SubTotal");

                            b1.HasKey("SaleId");

                            b1.ToTable("Sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "TaxTotal", b1 =>
                        {
                            b1.Property<Guid>("SaleId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TaxTotal");

                            b1.HasKey("SaleId");

                            b1.ToTable("Sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("SaleId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("SaleId");

                            b1.ToTable("Sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "Total", b1 =>
                        {
                            b1.Property<Guid>("SaleId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Total");

                            b1.HasKey("SaleId");

                            b1.ToTable("Sales");

                            b1.WithOwner()
                                .HasForeignKey("SaleId");
                        });

                    b.Navigation("SubTotal")
                        .IsRequired();

                    b.Navigation("TaxTotal")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();

                    b.Navigation("Total")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.SaleDetail", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Inventory.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Sales.Sale", null)
                        .WithMany("Details")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("SaleDetailId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("UnitType");

                            b1.Property<string>("UnitLabel")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("UnitLabel");

                            b1.Property<decimal>("Value")
                                .HasColumnType("decimal(18,4)")
                                .HasColumnName("Quantity");

                            b1.HasKey("SaleDetailId");

                            b1.ToTable("SaleDetails");

                            b1.WithOwner()
                                .HasForeignKey("SaleDetailId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "SubTotal", b1 =>
                        {
                            b1.Property<Guid>("SaleDetailId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SubTotal");

                            b1.HasKey("SaleDetailId");

                            b1.ToTable("SaleDetails");

                            b1.WithOwner()
                                .HasForeignKey("SaleDetailId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "TaxAmount", b1 =>
                        {
                            b1.Property<Guid>("SaleDetailId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TaxAmount");

                            b1.HasKey("SaleDetailId");

                            b1.ToTable("SaleDetails");

                            b1.WithOwner()
                                .HasForeignKey("SaleDetailId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("SaleDetailId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("UnitPrice");

                            b1.HasKey("SaleDetailId");

                            b1.ToTable("SaleDetails");

                            b1.WithOwner()
                                .HasForeignKey("SaleDetailId");
                        });

                    b.Navigation("Quantity")
                        .IsRequired();

                    b.Navigation("SubTotal")
                        .IsRequired();

                    b.Navigation("TaxAmount")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.Shift", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.HumanResources.Employee", null)
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "ActualCashAtClose", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("ActualCashAtClose");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "InitialCash", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("InitialCash");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "TotalCardSales", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalCardSales");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "TotalCashSales", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalCashSales");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "TotalCreditSales", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalCreditSales");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "TotalTransferSales", b1 =>
                        {
                            b1.Property<Guid>("ShiftId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("TotalTransferSales");

                            b1.HasKey("ShiftId");

                            b1.ToTable("Shifts");

                            b1.WithOwner()
                                .HasForeignKey("ShiftId");
                        });

                    b.Navigation("ActualCashAtClose");

                    b.Navigation("InitialCash")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();

                    b.Navigation("TotalCardSales")
                        .IsRequired();

                    b.Navigation("TotalCashSales")
                        .IsRequired();

                    b.Navigation("TotalCreditSales")
                        .IsRequired();

                    b.Navigation("TotalTransferSales")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.CashBox", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "Balance", b1 =>
                        {
                            b1.Property<Guid>("CashBoxId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Balance");

                            b1.HasKey("CashBoxId");

                            b1.ToTable("CashBoxes");

                            b1.WithOwner()
                                .HasForeignKey("CashBoxId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("CashBoxId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("CashBoxId");

                            b1.ToTable("CashBoxes");

                            b1.WithOwner()
                                .HasForeignKey("CashBoxId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.CashDrawer", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Sales.Shift", null)
                        .WithMany()
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "CurrentBalance", b1 =>
                        {
                            b1.Property<Guid>("CashDrawerId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CurrentBalance");

                            b1.HasKey("CashDrawerId");

                            b1.ToTable("CashDrawers");

                            b1.WithOwner()
                                .HasForeignKey("CashDrawerId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "OpeningBalance", b1 =>
                        {
                            b1.Property<Guid>("CashDrawerId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("OpeningBalance");

                            b1.HasKey("CashDrawerId");

                            b1.ToTable("CashDrawers");

                            b1.WithOwner()
                                .HasForeignKey("CashDrawerId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("CashDrawerId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("CashDrawerId");

                            b1.ToTable("CashDrawers");

                            b1.WithOwner()
                                .HasForeignKey("CashDrawerId");
                        });

                    b.Navigation("CurrentBalance")
                        .IsRequired();

                    b.Navigation("OpeningBalance")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.Expense", b =>
                {
                    b.HasOne("TuColmadoRD.Core.Domain.Entities.Treasury.CashBox", null)
                        .WithMany()
                        .HasForeignKey("CashBoxId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("ExpenseId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("Expenses");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("ExpenseId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("ExpenseId");

                            b1.ToTable("Expenses");

                            b1.WithOwner()
                                .HasForeignKey("ExpenseId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Treasury.PettyCash", b =>
                {
                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "Balance", b1 =>
                        {
                            b1.Property<Guid>("PettyCashId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Balance");

                            b1.HasKey("PettyCashId");

                            b1.ToTable("PettyCashes");

                            b1.WithOwner()
                                .HasForeignKey("PettyCashId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.Money", "MaxLimit", b1 =>
                        {
                            b1.Property<Guid>("PettyCashId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MaxLimit");

                            b1.HasKey("PettyCashId");

                            b1.ToTable("PettyCashes");

                            b1.WithOwner()
                                .HasForeignKey("PettyCashId");
                        });

                    b.OwnsOne("TuColmadoRD.Core.Domain.ValueObjects.TenantIdentifier", "TenantId", b1 =>
                        {
                            b1.Property<Guid>("PettyCashId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid")
                                .HasColumnName("TenantId");

                            b1.HasKey("PettyCashId");

                            b1.ToTable("PettyCashes");

                            b1.WithOwner()
                                .HasForeignKey("PettyCashId");
                        });

                    b.Navigation("Balance")
                        .IsRequired();

                    b.Navigation("MaxLimit")
                        .IsRequired();

                    b.Navigation("TenantId")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Customers.Customer", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Purchasing.PurchaseOrder", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("TuColmadoRD.Core.Domain.Entities.Sales.Sale", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
